### ISSUE TITLE
Syntax highlight is turned off

### ISSUE THREAD

**Issue by jjconti** [minad/iruby#28]
(Sometimes) After close and re open a notebook (not the browser tab, the entire server) syntax highlight is off in the saved cells. If I delete the cell content and retype it, it's still off. If I delete the cell and add a new one, syntax highlight is one again.

Have you experiment this?

![screenshot from 2014-07-22 17 30 27_iruby](https://cloud.githubusercontent.com/assets/53265/3664665/1d51aea2-11df-11e4-9bf4-3f237444822b.png)

**Comment by minad** [comment]
I moved this issue to Sciruby/iruby#6
