### ISSUE TITLE
More description about installation

### ISSUE THREAD

**Issue by domitry** [minad/iruby#31]
Hi,

I tried IRuby in Ubuntu and Windows, and a user of nyaplot did in Mac OS X. I found that the installation  seems to be a bit complicated especially in Mac OS and Windows, and I think it is better to write more about it in README.md.

There is some description about installation of IRuby in my repository, and If you allow me I will move those lines to README of this repository and make a pull-request.
https://github.com/domitry/nyaplot#install-iruby-notebook

Thank you

**Comment by minad** [comment]
Closed in favour of SciRuby/iruby#1, please comment there.
