### ISSUE TITLE
iruby command always replaces static directory in the profile

### ISSUE THREAD

**Issue by jnv** [minad/iruby#33]
Custom `static` directory is always replaced by symlink to the gem's static directory, making it impossible to customize Notebook's behaviour (e.g. load extensions through `custom.js`, modify stylesheets through `custom.css` etc.) without messing with gem's static files.

This happens because `create_profile` [runs every time](https://github.com/minad/iruby/blob/fda30d610786db4e2929554de37ba25972846f36/lib/iruby/command.rb#L63) when using `iruby` command line wrapper, which is pretty invasive. I think `iruby` command should attempt to create profile only for `iruby profile create` or when `--init` option is used with other subcommands. Alternatively, there could be an opposite switch, say `--no-init`, which prevents `create_profile` from being run.

Current workaround for me is to call `ipython` directly with `--ipython-dir=~/.config/iruby`, though I would like to know if there is another alternative, e.g. configuration option to load an additional JS by notebook.

**Comment by minad** [comment]
Yes it is intrusive, this will be fixed with #39

**Comment by minad** [comment]
Closed in favour of SciRuby/iruby#1, please comment there.
