### ISSUE TITLE
typos prevent rmagick images to be displayed

### ISSUE THREAD

**Issue by morus** [minad/iruby#46]
Hi,

the logic for displaying image magick has typos in the namespaces for magick and minimagick.
The k is missing.
In display.rb lines 230ff should read
       match do |obj|
        defined?(Magick::Image) && Magick::Image === obj ||
        defined?(MiniMagick::Image) && MiniMagick::Image === obj
      end

I can provide a patch if that helps, but it's really just the addition for 4 final 'k'.

I didn't test the MiniMagick case, but I checked that the 'k' is required in that case either.

Thanks for iruby,
best
  Morus

**Comment by minad** [comment]
this is fixed I think?
