### ISSUE TITLE
Parsing latex equations in iruby notebook

### ISSUE THREAD

**Issue by v0dro** [minad/iruby#49]
Being able to express latex equations in iruby would be great. [Heres](http://nbviewer.ipython.org/github/ipython/ipython/blob/2.x/examples/Notebook/Typesetting%20Math%20Using%20MathJax.ipynb) an example using an iPython notebook.

**Comment by domitry** [comment]
IRuby can convert latex text to elegant math symbols even now.
Have a look at the notebook:
http://nbviewer.ipython.org/github/domitry/mathmas/blob/master/examples/Mathmas_develop.ipynb
or my code:
https://github.com/domitry/mathmas

**Comment by v0dro** [comment]
Ah my bad.
