### ISSUE TITLE
Make custom css using less

### ISSUE THREAD

**Issue by Carreau** [minad/iruby#5]
IPython itself compile its css [using less](https://github.com/ipython/ipython/tree/master/IPython/html/static/style).

May I suggest compiling a full IRuby css using less, by overriding variable like 
`@LinkColor` ? 

Especially because this has repercussion into Bootstrap theme, where button color primary is derived from LinkColor... etc

I suppose you like to automatize this in ruby, I don't know how to do it, but if you need change in IPython to help you, I guess it is feasible.

I'll also be happy to get a PR [against nbviewer](https://github.com/ipython/nbviewer/tree/master/static) that include this css file and can start to add the logic that switches css if it detects the notebook is ruby based.

**Comment by minad** [comment]
Closed in favour of SciRuby/iruby#1, please comment there.
