### ISSUE TITLE
iRuby looks/acts like iPython

### ISSUE THREAD

**Issue by seanodell** [minad/iruby#50]
I just installed iRuby, and after firing it up with "iruby notebook" every notebook I create and run gives me Python-specific errors. It's as if, even though I started iruby, it started up as a plain old ipython notebook.

I just pip installed ipython and gem installed iruby today. ipython version is 2.3.1.

Any ideas why everything runs as python when I run iruby notebook?

**Comment by minad** [comment]
Can you check the iruby profile if it refers to the correct kernel?

~/.config/iruby/profile_default/ipython_config.py:
~~~
c.KernelManager.kernel_cmd = ["~/bin/iruby", "kernel", "{connection_file}"]
~~~

**Comment by seanodell** [comment]
That file doesn't exist. Is that something I am supposed to create, or is that installed when I install iRuby?

**Comment by seanodell** [comment]
Ohp. Wait. I saw an error saying that ~/.config wasn't writable. Probably somewhere a line of code should create that when it doesn't exist. I created it by hand and now everything works as expected.

**Comment by minad** [comment]
Ok, thx for reporting. There are many cases to catch. However it is not necessary to fix this, since the handling of the configuration has changed with IPython 3.
