### ISSUE TITLE
Require works in iruby console but not in iruby notebook

### ISSUE THREAD

**Issue by Ellyster** [minad/iruby#53]
I've try to require a couple of self installed libraries like [KantanSGF](https://github.com/boj/kantan-sgf) or [SGFparser](https://github.com/Trevoke/SGFParser)

And it works in the IRuby console:
![kantan-sgf-0_0_2_ _bash_ _80x24](https://cloud.githubusercontent.com/assets/4518921/5904891/5e476f94-a5cf-11e4-87a9-ed3d69cf508a.png)

But not in the IRuby notebook:
![untitled0](https://cloud.githubusercontent.com/assets/4518921/5905032/63f186ae-a5d0-11e4-968f-a3a919bcac3f.png)

Even though the gem is in the ```$LOAD_PATH``` of ruby.

**Comment by minad** [comment]
This could be either due to bundler or due to a wrong $LOAD_PATH.

**Comment by Ellyster** [comment]
Both look like there are working properly anywhere.... the only place where it fails is in iRuby notebook
